#pragma once

#define ZONIX_VERSION_MAJOR 0
#define ZONIX_VERSION_MINOR 10
#define ZONIX_VERSION_PATCH 1

#define _ZONIX_STR(x) #x
#define ZONIX_STR(x)  _ZONIX_STR(x)

#define ZONIX_VERSION_STRING \
    ZONIX_STR(ZONIX_VERSION_MAJOR) "." ZONIX_STR(ZONIX_VERSION_MINOR) "." ZONIX_STR(ZONIX_VERSION_PATCH)

#define ZONIX_CODENAME "Genesis"

#define ZONIX_BUILD_DATE        "Mar 24 2026"
#define ZONIX_BUILD_TIME        "15:23:32"
#define ZONIX_BUILD_NUMBER 1
